PORTNAME=	ipgen
DISTVERSION=	0.0.1
CATEGORIES=	net

MAINTAINER=	y@trombik.org
COMMENT=	Packet traffic generator that uses netmap or XDP
WWW=		https://github.com/iij/ipgen

LICENSE=	MIT

USES=	gmake
USE_GITHUB=	yes
GH_TUPLE=	iij:ipgen:da26c15

MAKEFILE=	GNUmakefile

.include <bsd.port.mk>
